defaults:
  - _self_
  - paths: ../utils/paths
  - cams: ../utils/cam_mac_address
  - ssh: ../utils/ssh

raw_video_path: "/mnt/geosense/cameras/F4E2C678D10D/08/21/video/F4E2C678D10D_1_0.mp4"

dst_dir: /mnt/geosense/cameras
remote_dir: /volume1/videos
#dst_dir: /mnt/geosense/cameras/F4E2C678D10D/08/21/frames

set_size: 6

NVR:
  src_dir: /srv/unifi-protect/video
  dst_dir: /volume1/videos