defaults:
  - _self_
  - paths: ../utils/paths
  - cams: ../utils/cam_mac_address
  - ssh: ../utils/ssh
  - pylos: ../utils/pylos
  - calibration: ../utils/calibration

raw_video_path: "/mnt/geosense/cameras/F4E2C678D10D/08/21/video/F4E2C678D10D_1_0.mp4"

dst_dir: /mnt/geosense/cameras
remote_dir: /volume1/videos
#dst_dir: /mnt/geosense/cameras/F4E2C678D10D/08/21/frames

set_size: 1 # Among the 6 frames, 1 frame will be kept (highest quality)
interval: 1 # Every 3 set will be kept (10s --> 6 frames --> 3 = one image per 3 minutes)

NVR:
  src_dir: /srv/unifi-protect/video
  dst_dir: /volume1/videos